#!/usr/bin/env python3
"""Assemble schema/pagespec.schema.json (JSON Schema draft-07) from the repo's own contracts.

Inputs (all inside design-repo/): sections/*.json (content schemas, variants, motion),
templates/templates.json (template enum), tokens/00-foundation/motion-patterns.json,
assets/asset-roles.json (closed assetRole enum), data/blog-posts.json (slug enum).

Usage:  python3 schema/build_schema.py          # rewrite pagespec.schema.json
        python3 schema/build_schema.py --check  # exit 1 if the committed file differs (drift)
"""
import json, os, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGESPEC_VERSION = "1.0.0"

# href: internal route ('/', '/a/b/', '/blog?category=X'), mailto:, tel:. Nothing else (NO_OUTBOUND_LINKS).
HREF_PATTERN = r"^(?:/(?:[a-z0-9-]+/)*(?:[a-z0-9-]+/?)?(?:\?[a-z]+=[A-Za-z0-9%+._-]+(?:&[a-z]+=[A-Za-z0-9%+._-]+)*)?|mailto:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[a-z]{2,}|tel:\+?[0-9]{6,15})$"


def load(rel):
    with open(os.path.join(REPO, rel), encoding="utf-8") as f:
        return json.load(f)


def defname(section_id):
    return "content_" + section_id.replace(".", "__").replace("-", "_")


def build():
    sections = [load("sections/" + f) for f in sorted(os.listdir(os.path.join(REPO, "sections"))) if f.endswith(".json")]
    templates = load("templates/templates.json")["templates"]
    mp = load("tokens/00-foundation/motion-patterns.json")
    roles = load("assets/asset-roles.json")["roles"]
    slugs = [p["slug"] for p in load("data/blog-posts.json")["posts"]]

    defs = {
        "href": {"type": "string", "pattern": HREF_PATTERN, "description": "Internal route, mailto: or tel: only (NO_OUTBOUND_LINKS)."},
        "link": {"type": "object", "additionalProperties": False, "required": ["label", "href"],
                 "properties": {"label": {"type": "string", "minLength": 1}, "href": {"$ref": "#/definitions/href"}}},
        "media": {"type": "object", "additionalProperties": False, "required": ["assetRole", "alt"],
                  "properties": {"assetRole": {"enum": sorted(roles)}, "asset": {"type": "string", "pattern": "^/assets/[A-Za-z0-9/_.-]+$"},
                                 "placeholder": {"type": "boolean"}, "alt": {"type": "string"}}},
        "postSlug": {"enum": slugs},
        "motion": {"type": "object", "additionalProperties": False, "required": ["patterns", "reducedMotionFallback"],
                   "properties": {"patterns": {"type": "array", "minItems": 1, "uniqueItems": True, "items": {"enum": sorted(mp["patterns"])}},
                                  "reducedMotionFallback": {"enum": sorted(mp["reducedMotionFallbacks"])}}},
    }
    branches = []
    for s in sections:
        defs[defname(s["id"])] = s["content"]["schema"]
        for k, v in s["content"].get("blockSchemas", {}).items():
            defs["block_" + k] = v
        for k, v in s["content"].get("richSchemas", {}).items():
            defs["rich_" + k.replace("-", "_")] = v
        then = {"properties": {"content": {"$ref": "#/definitions/" + defname(s["id"])},
                               "motion": {"properties": {"patterns": {"items": {"enum": s["motion"]["allowedPatterns"]}},
                                                         "reducedMotionFallback": {"const": s["motion"]["reducedMotionFallback"]}}}}}
        if s["variants"]:
            then["required"] = ["variant"]
            then["properties"]["variant"] = {"enum": s["variants"]}
        else:
            then["not"] = {"required": ["variant"]}
        branches.append({"if": {"properties": {"section": {"const": s["id"]}}, "required": ["section"]}, "then": then})
    defs["node"] = {"type": "object", "additionalProperties": False, "required": ["section", "content", "motion"],
                    "properties": {"section": {"enum": [s["id"] for s in sections]}, "variant": {"type": "string"},
                                   "content": {"type": "object"}, "motion": {"$ref": "#/definitions/motion"}},
                    "allOf": branches}
    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "impilo-clone/pagespec.schema.json",
        "title": "Impilo clone PageSpec",
        "description": "Machine contract for a generated page composition. Generated by schema/build_schema.py from sections/, templates/, assets/, tokens/ and data/ - do not hand-edit.",
        "type": "object", "additionalProperties": False,
        "required": ["pageSpecVersion", "template", "route", "meta", "nodes"],
        "properties": {
            "pageSpecVersion": {"const": PAGESPEC_VERSION},
            "template": {"enum": sorted(templates)},
            "route": {"type": "string", "pattern": r"^/(?:[a-z0-9-]+/)*$"},
            "meta": {"type": "object", "additionalProperties": False, "required": ["title"],
                     "properties": {"title": {"type": "string", "minLength": 1, "maxLength": 120}, "description": {"type": "string", "maxLength": 320}}},
            "nodes": {"type": "array", "minItems": 3, "items": {"$ref": "#/definitions/node"}},
        },
        "definitions": defs,
    }


def dumps(obj):
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


if __name__ == "__main__":
    out = os.path.join(REPO, "schema", "pagespec.schema.json")
    text = dumps(build())
    if "--check" in sys.argv:
        cur = open(out, encoding="utf-8").read() if os.path.exists(out) else ""
        if cur != text:
            print("SCHEMA DRIFT: schema/pagespec.schema.json differs from what the contracts generate")
            sys.exit(1)
        print("schema up to date")
    else:
        open(out, "w", encoding="utf-8").write(text)
        print("wrote", os.path.relpath(out, REPO))
